name: FastItemEditor
version: '${version}'
main: fr.mathilde.FastItemEditor
api-version: '1.20'
author: Mathilde
description: FastItemEditor is a simple GUI based plugin that allows you to easily edit items in your inventory.
commands:
  fastitemeditor:
    description: "Opens the FastItemEditor GUI"
    usage: /<command>
    aliases: [ fie ]
